[package]
name = "tricky-throws"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
bevy = "0.8.0"
bevy_rapier2d = "0.16.1"
rand = { version = "0.8.5", features = ["small_rng"] }
union-find = "0.4.1"